app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: babu
    pool-size: 30

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
